### ISSUE TITLE
SubmitChanges method saves an empty file if loaded to editor file was not modified

### ISSUE THREAD

**Issue by dondrakon** [abbaye/WpfHexEditorControl#48]
**Describe the bug**
SubmitChanges method saves an empty file if loaded to editor file was not modified

**To Reproduce**
1. Launch WpfHexEditor.Sample.NET47 (or NET451) project
2. Click File -> Open
3. Open a text file
4. **Without changing in the hex editor (important!)** click File ->Save as...
5. Create a new file, select it and press Save button

**Expected behavior**
Opened in hex editor file stored to the new file

**Actual behavior**
1. New file created and empty
2. Hex editor opened this empty file

**Desktop (please complete the following information):**
 - OS: Windows 10 1903

**Additional context**
 - Visual Studio 2019
- Test file:
[php_info.txt](https://github.com/abbaye/WpfHexEditorControl/files/3434956/php_info.txt)

**Comment by abbaye** [comment]
Good! :)

**Comment by abbaye** [comment]
It's fixed now :smile:

**Comment by dondrakon** [comment]
I pulled your update but the issue is still reproduced. Command thread does not enter to the fixed method.

**Comment by abbaye** [comment]
I will check this tommorow mornings

**Comment by abbaye** [comment]
I will check this when I will at home next Thursday. I'm at camp now :smiley:

**Comment by abbaye** [comment]
I think it will be ok now

**Comment by dondrakon** [comment]
Yes! The issue is not reproduced anymore. Thank you!
